# Lesson 10 Numpy Tutorial
Computer Programming I

University of Uppsala

Fall 2020

Anders Jakobsson


The `blackcellmagic` extension is loaded just to be able to use the `black`formatter in notebook cells.

In [1]:
%load_ext blackcellmagic

### The Basics
#### An example

In [2]:
import numpy as np

a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
a.itemsize

8

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

#### Array Creation

In [11]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int64')

In [13]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [14]:
a = np.array(1,2,3,4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [15]:
a = np.array([1,2,3,4])

In [16]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [17]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [18]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

`np.empty` kan man kolla mer på, ser ut som kopia på b ovan 2020-10-04

In [23]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [25]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [27]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [28]:
from numpy import pi
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [32]:
x = np.linspace(0, 2 * pi, 100)
f = np.sin(x)
x, f

(array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
        0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
        0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
        0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
        1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
        1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
        1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
        2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
        2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
        2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
        3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
        3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
        3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
        4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
        4.44265628, 4.5061228 , 4.56958931, 4.63

#### Printing Arrays

In [33]:
a = np.arange(6) 
print(a)

[0 1 2 3 4 5]


In [34]:
b = np.arange(12).reshape(4,3) 
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [35]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [36]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [37]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [40]:
import sys

np.set_printoptions(threshold=sys.maxsize)
np.get_printoptions()

{'edgeitems': 3,
 'threshold': 9223372036854775807,
 'floatmode': 'maxprec',
 'precision': 8,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False}

#### Basic Operations

In [42]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [44]:
c = a - b
c

array([20, 29, 38, 47])

In [45]:
b**2

array([0, 1, 4, 9])

In [46]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [47]:
a<35

array([ True,  True, False, False])

In [49]:
A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

In [50]:
A * B 

array([[2, 0],
       [0, 4]])

In [51]:
A @ B

array([[5, 4],
       [3, 4]])

In [52]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [55]:
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
rg

Generator(PCG64) at 0x11A2CD130

In [56]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [57]:
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [58]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [59]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [60]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [61]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [63]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [64]:
c.dtype.name

'float64'

In [66]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [67]:
d.dtype.name

'complex128'

In [68]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [69]:
a.sum()

3.1057109529998157

In [70]:
a.min()

0.027559113243068367

In [71]:
a.max()

0.8277025938204418

In [72]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [74]:
b.min(axis=1)

array([0, 4, 8])

In [75]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

#### Universal Functions

In [76]:
B = np.arange(3)
B

array([0, 1, 2])

In [77]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [78]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [79]:
C = np.array([2.0, -1.0, 4.0])
np.add(B, C)

array([2., 0., 6.])

#### Indexing, Slicing and Iterating

In [80]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [81]:
a[2]

8

In [82]:
a[2:5]

array([ 8, 27, 64])

In [83]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [84]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [85]:
for i in a:
    print(i ** (1 / 3.0))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [86]:
def f(x, y):
    return 10 * x + y

In [87]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [88]:
b[2,3]

23

In [89]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [90]:
b[ : ,1]

array([ 1, 11, 21, 31, 41])

In [91]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [92]:
b[-1] 

array([40, 41, 42, 43])

In [93]:
c = np.array([[[0, 1, 2],
               [10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]],])
c.shape

(2, 2, 3)

In [94]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [95]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [96]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [97]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
